# Generated by Django 2.1.4 on 2019-03-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_users_vk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_point', models.TextField()),
                ('id_concert', models.TextField()),
                ('name_concert', models.TextField()),
                ('list_id_users', models.TextField()),
                ('winner', models.TextField()),
                ('task_time', models.TextField()),
                ('gift_title', models.TextField()),
                ('gift_description', models.TextField()),
                ('gift_timeleft', models.TextField()),
                ('gift_main', models.TextField()),
                ('gift_points', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='users_vk',
            name='close_tasks',
        ),
        migrations.AlterField(
            model_name='users_vk',
            name='active_tasks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users_vk',
            name='failed_tasks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users_vk',
            name='id_vk',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users_vk',
            name='points',
            field=models.TextField(),
        ),
    ]
