# Generated by Django 2.1.4 on 2019-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190323_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
